#include "MainWindow.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QLabel>
#include <QMessageBox>
#include <QProcess>
#include <QRegularExpression>
#include <QSet>
#include <QStatusBar>
#include <QTextStream>

#include <algorithm>
#include <cmath>

#include <vtkActor.h>
#include <vtkCell.h>
#include <vtkDoubleArray.h>
#include <vtkGenericOpenGLRenderWindow.h>
#include <vtkLookupTable.h>
#include <vtkPointData.h>
#include <vtkPolyData.h>
#include <vtkPolyDataMapper.h>
#include <vtkProperty.h>
#include <vtkScalarBarActor.h>

namespace {

double signedTetVolume6(
    const VolumeNode &a,
    const VolumeNode &b,
    const VolumeNode &c,
    const VolumeNode &d)
{
    const double ux = b.x - a.x;
    const double uy = b.y - a.y;
    const double uz = b.z - a.z;
    const double vx = c.x - a.x;
    const double vy = c.y - a.y;
    const double vz = c.z - a.z;
    const double wx = d.x - a.x;
    const double wy = d.y - a.y;
    const double wz = d.z - a.z;
    return ux * (vy * wz - vz * wy)
        - uy * (vx * wz - vz * wx)
        + uz * (vx * wy - vy * wx);
}

} // namespace

bool MainWindow::writeCalculixInput(const QString &filePath) const
{
    if (volumeMesh_.nodes.isEmpty() || volumeMesh_.tetrahedra.isEmpty()) {
        QMessageBox::warning(const_cast<MainWindow *>(this), "CalculiX", "Generate a Netgen volume mesh before exporting.");
        return false;
    }

    QSet<int> constrainedNodeIds;
    for (const ConstraintFaceGroup &group : constraintFaceGroups_) {
        if (!group.enabled) {
            continue;
        }
        for (int sourceFaceId : group.sourceFaceIds) {
            const auto it = volumeMesh_.constraintNodeIdsByMarker.constFind(sourceFaceId);
            if (it != volumeMesh_.constraintNodeIdsByMarker.constEnd()) {
                constrainedNodeIds.unite(it.value());
            }
        }
    }
    if (constrainedNodeIds.isEmpty()) {
        QMessageBox::warning(const_cast<MainWindow *>(this), "CalculiX", "No boundary mesh nodes were found for the selected constraint faces.");
        return false;
    }

    int enabledLoadCount = 0;
    int mappedLoadCount = 0;
    for (const LoadingDevice &device : loadingDevices_) {
        if (device.enabled && device.meshNodeId >= 0 && device.meshNodeId < volumeMesh_.nodes.size()) {
            ++mappedLoadCount;
        }
        if (device.enabled) {
            ++enabledLoadCount;
        }
    }
    if (enabledLoadCount <= 0 || mappedLoadCount != enabledLoadCount) {
        QMessageBox::warning(const_cast<MainWindow *>(this), "CalculiX", "Pick every enabled load point on the generated boundary mesh before exporting.");
        return false;
    }

    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QMessageBox::warning(const_cast<MainWindow *>(this), "CalculiX", "Could not write CalculiX input file.");
        return false;
    }

    QTextStream out(&file);
    out << "*HEADING\n";
    out << "Generated by VisualizationPrototype\n";
    out << "*NODE\n";
    for (int i = 0; i < volumeMesh_.nodes.size(); ++i) {
        const VolumeNode &node = volumeMesh_.nodes.at(i);
        out << i + 1 << ", " << node.x << ", " << node.y << ", " << node.z << "\n";
    }

    out << "*ELEMENT, TYPE=C3D4, ELSET=MODEL_VOLUME\n";
    for (int i = 0; i < volumeMesh_.tetrahedra.size(); ++i) {
        const VolumeTetrahedron &tetrahedron = volumeMesh_.tetrahedra.at(i);
        int a = tetrahedron.a;
        int b = tetrahedron.b;
        int c = tetrahedron.c;
        int d = tetrahedron.d;
        if (a >= 0 && a < volumeMesh_.nodes.size()
            && b >= 0 && b < volumeMesh_.nodes.size()
            && c >= 0 && c < volumeMesh_.nodes.size()
            && d >= 0 && d < volumeMesh_.nodes.size()
            && signedTetVolume6(
                volumeMesh_.nodes.at(a),
                volumeMesh_.nodes.at(b),
                volumeMesh_.nodes.at(c),
                volumeMesh_.nodes.at(d)) < 0.0) {
            std::swap(b, c);
        }
        out << i + 1
            << ", " << a + 1
            << ", " << b + 1
            << ", " << c + 1
            << ", " << d + 1
            << "\n";
    }

    out << "*MATERIAL, NAME=DEFAULT_STEEL\n";
    out << "*ELASTIC\n";
    out << "210000., 0.3\n";
    out << "*SOLID SECTION, ELSET=MODEL_VOLUME, MATERIAL=DEFAULT_STEEL\n";

    out << "*BOUNDARY\n";
    QVector<int> sortedConstrainedNodeIds(constrainedNodeIds.begin(), constrainedNodeIds.end());
    std::sort(sortedConstrainedNodeIds.begin(), sortedConstrainedNodeIds.end());
    for (int nodeId : sortedConstrainedNodeIds) {
        out << nodeId + 1 << ", 1, 3, 0.0\n";
    }

    out << "*STEP\n";
    out << "*STATIC\n";
    out << "*CLOAD\n";
    for (const LoadingDevice &device : loadingDevices_) {
        if (!device.enabled || device.meshNodeId < 0 || device.meshNodeId >= volumeMesh_.nodes.size()) {
            continue;
        }
        QVector3D normal = device.direction.lengthSquared() > 1e-8f ? device.direction.normalized() : QVector3D(0.0f, 0.0f, 1.0f);
        out << device.meshNodeId + 1 << ", 1, " << device.currentLoad * normal.x() << "\n";
        out << device.meshNodeId + 1 << ", 2, " << device.currentLoad * normal.y() << "\n";
        out << device.meshNodeId + 1 << ", 3, " << device.currentLoad * normal.z() << "\n";
    }
    out << "*NODE FILE\n";
    out << "U\n";
    out << "*EL FILE\n";
    out << "S, E\n";
    out << "*END STEP\n";

    return true;
}
bool MainWindow::applyCalculixResult(const QString &filePath)
{
    if (volumeMesh_.nodes.isEmpty() || !meshBoundaryData_ || meshBoundaryData_->GetNumberOfPoints() == 0) {
        QMessageBox::warning(this, "CalculiX Result", "Generate a Netgen volume mesh before opening a result file.");
        return false;
    }

    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        QMessageBox::warning(this, "CalculiX Result", "Could not open result file.");
        return false;
    }

    QVector<double> displacementMagnitude(volumeMesh_.nodes.size(), 0.0);
    QVector<bool> hasDisplacement(volumeMesh_.nodes.size(), false);
    bool inDisplacementBlock = false;
    int parsedCount = 0;
    double maxMagnitude = 0.0;
    const QRegularExpression numberPattern(QStringLiteral("[-+]?\\d*\\.?\\d+(?:[Ee][-+]?\\d+)?"));

    while (!file.atEnd()) {
        const QString line = QString::fromLocal8Bit(file.readLine());
        const QString trimmed = line.trimmed();
        if (trimmed.startsWith("-4")) {
            inDisplacementBlock = trimmed.contains("DISP");
            continue;
        }
        if (inDisplacementBlock && trimmed.startsWith("-3")) {
            break;
        }
        if (!inDisplacementBlock || !trimmed.startsWith("-1")) {
            continue;
        }

        QVector<double> values;
        auto matchIterator = numberPattern.globalMatch(trimmed);
        while (matchIterator.hasNext()) {
            const QRegularExpressionMatch match = matchIterator.next();
            values.push_back(match.captured(0).toDouble());
        }
        if (values.size() < 5) {
            continue;
        }

        const int nodeId = int(values.at(1)) - 1;
        if (nodeId < 0 || nodeId >= displacementMagnitude.size()) {
            continue;
        }
        const double dx = values.at(2);
        const double dy = values.at(3);
        const double dz = values.at(4);
        const double magnitude = std::sqrt(dx * dx + dy * dy + dz * dz);
        displacementMagnitude[nodeId] = magnitude;
        hasDisplacement[nodeId] = true;
        maxMagnitude = std::max(maxMagnitude, magnitude);
        ++parsedCount;
    }

    if (parsedCount == 0) {
        QMessageBox::warning(this, "CalculiX Result", "No nodal displacement block was found in the .frd file.");
        return false;
    }

    auto scalars = vtkSmartPointer<vtkDoubleArray>::New();
    scalars->SetName("DisplacementMagnitude");
    scalars->SetNumberOfComponents(1);
    scalars->SetNumberOfTuples(meshBoundaryData_->GetNumberOfPoints());
    for (vtkIdType i = 0; i < meshBoundaryData_->GetNumberOfPoints(); ++i) {
        const int nodeId = int(i);
        const double value = nodeId >= 0 && nodeId < displacementMagnitude.size() && hasDisplacement.at(nodeId)
            ? displacementMagnitude.at(nodeId)
            : 0.0;
        scalars->SetTuple1(i, value);
    }

    meshBoundaryData_->GetPointData()->SetScalars(scalars);
    meshBoundaryData_->Modified();

    const double upper = maxMagnitude > 0.0 ? maxMagnitude : 1.0;
    lookupTable_->SetRange(0.0, upper);
    if (scalarBar_) {
        scalarBar_->SetTitle("Displacement");
    }
    if (modelMapper_) {
        modelMapper_->ScalarVisibilityOff();
        modelMapper_->Update();
    }
    if (modelActor_) {
        modelActor_->SetVisibility(false);
    }
    if (meshBoundaryMapper_) {
        meshBoundaryMapper_->SetLookupTable(lookupTable_);
        meshBoundaryMapper_->ScalarVisibilityOn();
        meshBoundaryMapper_->SetScalarRange(0.0, upper);
        meshBoundaryMapper_->Update();
    }
    if (meshBoundaryActor_) {
        meshBoundaryActor_->SetVisibility(true);
        meshBoundaryActor_->GetProperty()->SetOpacity(1.0);
    }
    if (valueLabel_) {
        valueLabel_->setText(QString("Max displacement: %1").arg(maxMagnitude, 0, 'e', 3));
    }
    refreshWorkflowStatus();
    statusBar()->showMessage(QString("Loaded CalculiX displacement result from %1.").arg(QFileInfo(filePath).fileName()));
    renderWindow_->Render();
    return true;
}
void MainWindow::exportCalculixInput()
{
    if (!ensureProjectReady(QStringLiteral("exporting CalculiX input"))) {
        return;
    }

    const QString path = QDir(projectSubdir(QStringLiteral("solver"))).absoluteFilePath("model.inp");
    if (writeCalculixInput(path)) {
        refreshWorkflowStatus();
        statusBar()->showMessage("Exported CalculiX input: " + path);
        QMessageBox::information(this, "CalculiX", "Exported CalculiX input:\n" + path);
    }
}
void MainWindow::openCalculixResult()
{
    if (!ensureProjectReady(QStringLiteral("opening CalculiX results"))) {
        return;
    }

    const QString solverResult = QDir(projectSubdir(QStringLiteral("solver"))).absoluteFilePath("model.frd");
    if (QFile::exists(solverResult)) {
        applyCalculixResult(solverResult);
        return;
    }

    const QString resultPath = QDir(projectSubdir(QStringLiteral("results"))).absoluteFilePath("model.frd");
    if (QFile::exists(resultPath)) {
        applyCalculixResult(resultPath);
        return;
    }

    QMessageBox::warning(this, "CalculiX Result", "No project result file was found in solver/model.frd or results/model.frd.");
}
void MainWindow::runCalculixSolver()
{
    if (meshJobRunning_ || solverJobRunning_) {
        QMessageBox::information(this, "CalculiX", "A background task is already running. Wait for it to finish before starting CalculiX.");
        return;
    }
    if (!ensureProjectReady(QStringLiteral("running CalculiX"))) {
        return;
    }

    const QString workDir = projectSubdir(QStringLiteral("solver"));
    if (workDir.isEmpty()) {
        QMessageBox::warning(this, "CalculiX", "Could not create the project solver directory.");
        return;
    }

    const QString inpPath = QDir(workDir).absoluteFilePath("model.inp");
    if (!writeCalculixInput(inpPath)) {
        return;
    }

    const QString bundledCcx = "C:/msys64/ucrt64/bin/ccx.exe";
    const QString ccxProgram = QFile::exists(bundledCcx) ? bundledCcx : QString("ccx");

    solverProcess_ = new QProcess(this);
    solverProcess_->setWorkingDirectory(workDir);
    solverOutput_.clear();

    connect(solverProcess_, &QProcess::readyReadStandardOutput, this, [this]() {
        if (solverProcess_) {
            solverOutput_ += QString::fromLocal8Bit(solverProcess_->readAllStandardOutput());
        }
    });
    connect(solverProcess_, &QProcess::readyReadStandardError, this, [this]() {
        if (solverProcess_) {
            solverOutput_ += QString::fromLocal8Bit(solverProcess_->readAllStandardError());
        }
    });
    connect(solverProcess_, &QProcess::errorOccurred, this, [this](QProcess::ProcessError error) {
        if (error != QProcess::FailedToStart || !solverProcess_) {
            return;
        }
        solverJobRunning_ = false;
        QProcess *process = solverProcess_;
        solverProcess_ = nullptr;
        process->deleteLater();
        finishBackgroundProgress(QStringLiteral("CalculiX failed to start."));
        QMessageBox::warning(this, "CalculiX", "Could not start ccx. Install CalculiX or put ccx.exe on PATH.");
    });
    connect(solverProcess_, QOverload<int, QProcess::ExitStatus>::of(&QProcess::finished), this,
        [this, workDir](int exitCode, QProcess::ExitStatus exitStatus) {
            if (!solverProcess_) {
                return;
            }
            solverOutput_ += QString::fromLocal8Bit(solverProcess_->readAllStandardOutput());
            solverOutput_ += QString::fromLocal8Bit(solverProcess_->readAllStandardError());

            QProcess *process = solverProcess_;
            solverProcess_ = nullptr;
            process->deleteLater();
            solverJobRunning_ = false;

            const QString frdPath = QDir(workDir).absoluteFilePath("model.frd");
            const QString datPath = QDir(workDir).absoluteFilePath("model.dat");
            const QString resultsDir = projectSubdir(QStringLiteral("results"));
            if (!resultsDir.isEmpty()) {
                const QString resultFrdPath = QDir(resultsDir).absoluteFilePath("model.frd");
                const QString resultDatPath = QDir(resultsDir).absoluteFilePath("model.dat");
                if (QFile::exists(frdPath)) {
                    QFile::remove(resultFrdPath);
                    QFile::copy(frdPath, resultFrdPath);
                }
                if (QFile::exists(datPath)) {
                    QFile::remove(resultDatPath);
                    QFile::copy(datPath, resultDatPath);
                }
            }

            finishBackgroundProgress(QStringLiteral("CalculiX solve finished."));
            if (exitStatus != QProcess::NormalExit || exitCode != 0) {
                QMessageBox::warning(this, "CalculiX", QString("Solver exited with code %1.\n\n%2")
                    .arg(exitCode)
                    .arg(solverOutput_.left(1200)));
                return;
            }
            if (QFile::exists(frdPath)) {
                const bool loaded = applyCalculixResult(frdPath);
                refreshWorkflowStatus();
                QMessageBox::information(this, "CalculiX", QString("Solver finished. %1\n\n%2")
                    .arg(loaded ? "Displacement result was loaded." : "Result file was written, but displacement display was not loaded.")
                    .arg(solverOutput_.left(1200)));
            } else if (QFile::exists(datPath)) {
                refreshWorkflowStatus();
                QMessageBox::information(this, "CalculiX", "Solver finished. Result files were written.\n\n" + solverOutput_.left(1200));
                statusBar()->showMessage("CalculiX solve finished.");
            } else {
                QMessageBox::warning(this, "CalculiX", "Solver finished but no model.frd/model.dat was found.\n\n" + solverOutput_.left(1200));
            }
        });

    solverJobRunning_ = true;
    startBackgroundProgress(QStringLiteral("Running CalculiX solver..."));
    solverProcess_->start(ccxProgram, {"model"});
}
