#include "NetgenVolumeMesher.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QRegularExpression>
#include <QSet>
#include <QStandardPaths>
#include <QStringList>
#include <QTextStream>

#include <BRepBuilderAPI_MakeVertex.hxx>
#include <BRepExtrema_DistShapeShape.hxx>
#include <Bnd_Box.hxx>
#include <BRepBndLib.hxx>
#include <IFSelect_ReturnStatus.hxx>
#include <STEPControl_Reader.hxx>
#include <TopAbs.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shape.hxx>
#include <gp_Pnt.hxx>

#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>

namespace {

struct NetgenSurfaceFace {
    int a = -1;
    int b = -1;
    int c = -1;
    int marker = 0;
};

struct NetgenMesh {
    QVector<VolumeNode> nodes;
    QVector<VolumeTetrahedron> tetrahedra;
    QVector<NetgenSurfaceFace> surfaceFaces;
};

struct SelectedFace {
    int sourceFaceId = 0;
    TopoDS_Face face;
};

QString nextDataLine(QTextStream &stream)
{
    while (!stream.atEnd()) {
        const QString line = stream.readLine().trimmed();
        if (line.isEmpty() || line.startsWith('#')) {
            continue;
        }
        return line;
    }
    return QString();
}

QStringList splitDataLine(const QString &line)
{
    return line.split(QRegularExpression(QStringLiteral("\\s+")), Qt::SkipEmptyParts);
}

void writeBoundaryLegacyVtkFile(const QString &vtkPath, const VolumeMesh &mesh)
{
    QFile file(vtkPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        throw std::runtime_error("Could not write Netgen boundary VTK output.");
    }

    QTextStream out(&file);
    out << "# vtk DataFile Version 3.0\n";
    out << "Netgen boundary faces generated by VisualizationPrototype\n";
    out << "ASCII\n";
    out << "DATASET POLYDATA\n";
    out << "POINTS " << mesh.nodes.size() << " double\n";
    for (const VolumeNode &node : mesh.nodes) {
        out << node.x << " " << node.y << " " << node.z << "\n";
    }

    out << "POLYGONS " << mesh.boundaryFaces.size() << " " << mesh.boundaryFaces.size() * 4 << "\n";
    for (const VolumeBoundaryFace &face : mesh.boundaryFaces) {
        out << "3 " << face.a << " " << face.b << " " << face.c << "\n";
    }

    out << "CELL_DATA " << mesh.boundaryFaces.size() << "\n";
    out << "SCALARS BoundaryMarker int 1\n";
    out << "LOOKUP_TABLE default\n";
    for (const VolumeBoundaryFace &face : mesh.boundaryFaces) {
        out << face.marker << "\n";
    }
}

void writeVolumeLegacyVtkFile(const QString &vtkPath, const VolumeMesh &mesh)
{
    QFile file(vtkPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        throw std::runtime_error("Could not write Netgen volume VTK output.");
    }

    QTextStream out(&file);
    out << "# vtk DataFile Version 3.0\n";
    out << "Netgen volume mesh generated by VisualizationPrototype\n";
    out << "ASCII\n";
    out << "DATASET UNSTRUCTURED_GRID\n";
    out << "POINTS " << mesh.nodes.size() << " double\n";
    for (const VolumeNode &node : mesh.nodes) {
        out << node.x << " " << node.y << " " << node.z << "\n";
    }

    out << "CELLS " << mesh.tetrahedra.size() << " " << mesh.tetrahedra.size() * 5 << "\n";
    for (const VolumeTetrahedron &tetrahedron : mesh.tetrahedra) {
        out << "4 " << tetrahedron.a << " " << tetrahedron.b << " " << tetrahedron.c << " " << tetrahedron.d << "\n";
    }

    out << "CELL_TYPES " << mesh.tetrahedra.size() << "\n";
    for (int i = 0; i < mesh.tetrahedra.size(); ++i) {
        out << "10\n";
    }
}

void parseNetgenSectionCount(QTextStream &stream, int &count)
{
    const QStringList parts = splitDataLine(nextDataLine(stream));
    if (parts.isEmpty()) {
        throw std::runtime_error("Invalid Netgen .vol section count.");
    }
    count = parts.at(0).toInt();
}

NetgenMesh readNetgenVolFile(const QString &volPath)
{
    QFile file(volPath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        throw std::runtime_error("Could not open Netgen .vol output.");
    }

    NetgenMesh mesh;
    QTextStream stream(&file);
    while (!stream.atEnd()) {
        const QString section = nextDataLine(stream).toLower();
        if (section.isEmpty()) {
            break;
        }

        if (section == QStringLiteral("points")) {
            int count = 0;
            parseNetgenSectionCount(stream, count);
            mesh.nodes.reserve(count);
            for (int i = 0; i < count; ++i) {
                const QStringList parts = splitDataLine(nextDataLine(stream));
                if (parts.size() < 3) {
                    throw std::runtime_error("Invalid Netgen point row.");
                }
                mesh.nodes.push_back({parts.at(0).toDouble(), parts.at(1).toDouble(), parts.at(2).toDouble()});
            }
        } else if (section == QStringLiteral("surfaceelements")
                   || section == QStringLiteral("surfaceelementsuv")) {
            int count = 0;
            parseNetgenSectionCount(stream, count);
            mesh.surfaceFaces.reserve(count);
            for (int i = 0; i < count; ++i) {
                const QStringList parts = splitDataLine(nextDataLine(stream));
                if (parts.size() < 4) {
                    throw std::runtime_error("Invalid Netgen surface element row.");
                }

                const int marker = parts.at(0).toInt();
                int firstNodeColumn = parts.size() >= 8 && parts.at(4).toInt() == 3 ? 5 : parts.size() - 3;
                if (firstNodeColumn < 0 || firstNodeColumn + 2 >= parts.size()) {
                    throw std::runtime_error("Unsupported Netgen surface element format.");
                }

                const int a = parts.at(firstNodeColumn).toInt() - 1;
                const int b = parts.at(firstNodeColumn + 1).toInt() - 1;
                const int c = parts.at(firstNodeColumn + 2).toInt() - 1;
                if (a < 0 || b < 0 || c < 0) {
                    throw std::runtime_error("Netgen surface element references an invalid point id.");
                }
                mesh.surfaceFaces.push_back({a, b, c, marker});
            }
        } else if (section == QStringLiteral("volumeelements")) {
            int count = 0;
            parseNetgenSectionCount(stream, count);
            mesh.tetrahedra.reserve(count);
            for (int i = 0; i < count; ++i) {
                const QStringList parts = splitDataLine(nextDataLine(stream));
                if (parts.size() < 5) {
                    throw std::runtime_error("Invalid Netgen volume element row.");
                }

                int firstNodeColumn = parts.size() >= 6 && parts.at(1).toInt() == 4 ? 2 : parts.size() - 4;
                if (firstNodeColumn < 0 || firstNodeColumn + 3 >= parts.size()) {
                    throw std::runtime_error("Unsupported Netgen volume element format.");
                }

                const int a = parts.at(firstNodeColumn).toInt() - 1;
                const int b = parts.at(firstNodeColumn + 1).toInt() - 1;
                const int c = parts.at(firstNodeColumn + 2).toInt() - 1;
                const int d = parts.at(firstNodeColumn + 3).toInt() - 1;
                if (a < 0 || b < 0 || c < 0 || d < 0) {
                    throw std::runtime_error("Netgen volume element references an invalid point id.");
                }
                mesh.tetrahedra.push_back({a, b, c, d});
            }
        }
    }

    if (mesh.nodes.isEmpty() || mesh.surfaceFaces.isEmpty()) {
        throw std::runtime_error("Netgen .vol did not contain points and surface elements.");
    }
    return mesh;
}

QVector<SelectedFace> readSelectedStepFaces(const QString &stepFilePath, const QSet<int> &constraintFaceIds)
{
    QVector<SelectedFace> selectedFaces;
    if (constraintFaceIds.isEmpty()) {
        return selectedFaces;
    }

    STEPControl_Reader reader;
    const IFSelect_ReturnStatus status = reader.ReadFile(stepFilePath.toLocal8Bit().constData());
    if (status != IFSelect_RetDone) {
        throw std::runtime_error("OCCT could not read the STEP/STP file for Netgen marker remapping.");
    }

    reader.TransferRoots();
    const TopoDS_Shape shape = reader.OneShape();
    if (shape.IsNull()) {
        throw std::runtime_error("The STEP/STP file did not contain a valid shape for Netgen marker remapping.");
    }

    int sourceFaceId = 0;
    for (TopExp_Explorer explorer(shape, TopAbs_FACE); explorer.More(); explorer.Next()) {
        ++sourceFaceId;
        if (!constraintFaceIds.contains(sourceFaceId)) {
            continue;
        }
        selectedFaces.push_back({sourceFaceId, TopoDS::Face(explorer.Current())});
    }

    return selectedFaces;
}

double meshTolerance(const NetgenMesh &mesh)
{
    if (mesh.nodes.isEmpty()) {
        return 1e-6;
    }

    double minX = std::numeric_limits<double>::max();
    double minY = std::numeric_limits<double>::max();
    double minZ = std::numeric_limits<double>::max();
    double maxX = std::numeric_limits<double>::lowest();
    double maxY = std::numeric_limits<double>::lowest();
    double maxZ = std::numeric_limits<double>::lowest();
    for (const VolumeNode &node : mesh.nodes) {
        minX = std::min(minX, node.x);
        minY = std::min(minY, node.y);
        minZ = std::min(minZ, node.z);
        maxX = std::max(maxX, node.x);
        maxY = std::max(maxY, node.y);
        maxZ = std::max(maxZ, node.z);
    }

    const double dx = maxX - minX;
    const double dy = maxY - minY;
    const double dz = maxZ - minZ;
    const double diagonal = std::sqrt(dx * dx + dy * dy + dz * dz);
    return std::max(1e-6, diagonal * 1e-5);
}

void remapNetgenSurfaceMarkersFromSelectedFaces(
    const QString &stepFilePath,
    NetgenMesh &mesh,
    const QSet<int> &constraintFaceIds)
{
    const QVector<SelectedFace> selectedFaces = readSelectedStepFaces(stepFilePath, constraintFaceIds);
    if (selectedFaces.isEmpty()) {
        return;
    }

    const double tolerance = meshTolerance(mesh);
    for (NetgenSurfaceFace &surfaceFace : mesh.surfaceFaces) {
        if (surfaceFace.a < 0 || surfaceFace.a >= mesh.nodes.size()
            || surfaceFace.b < 0 || surfaceFace.b >= mesh.nodes.size()
            || surfaceFace.c < 0 || surfaceFace.c >= mesh.nodes.size()) {
            continue;
        }

        const VolumeNode &a = mesh.nodes.at(surfaceFace.a);
        const VolumeNode &b = mesh.nodes.at(surfaceFace.b);
        const VolumeNode &c = mesh.nodes.at(surfaceFace.c);
        const gp_Pnt centroid(
            (a.x + b.x + c.x) / 3.0,
            (a.y + b.y + c.y) / 3.0,
            (a.z + b.z + c.z) / 3.0);
        const TopoDS_Shape vertex = BRepBuilderAPI_MakeVertex(centroid).Shape();

        int bestFaceId = 0;
        double bestDistance = std::numeric_limits<double>::max();
        for (const SelectedFace &selectedFace : selectedFaces) {
            BRepExtrema_DistShapeShape distance(vertex, selectedFace.face);
            distance.Perform();
            if (!distance.IsDone()) {
                continue;
            }
            const double value = distance.Value();
            if (value < bestDistance) {
                bestDistance = value;
                bestFaceId = selectedFace.sourceFaceId;
            }
        }

        if (bestFaceId > 0 && bestDistance <= tolerance) {
            surfaceFace.marker = bestFaceId;
        }
    }
}

void validateConstraintMarkers(const NetgenMesh &mesh, const QSet<int> &constraintFaceIds)
{
    if (constraintFaceIds.isEmpty()) {
        return;
    }

    QSet<int> netgenMarkers;
    for (const NetgenSurfaceFace &face : mesh.surfaceFaces) {
        if (face.marker > 0) {
            netgenMarkers.insert(face.marker);
        }
    }

    QVector<int> missing;
    for (int sourceFaceId : constraintFaceIds) {
        if (!netgenMarkers.contains(sourceFaceId)) {
            missing.push_back(sourceFaceId);
        }
    }
    if (!missing.isEmpty()) {
        std::sort(missing.begin(), missing.end());
        QStringList ids;
        for (int id : missing) {
            ids.push_back(QString::number(id));
        }
        throw std::runtime_error(QString(
            "Netgen surface markers did not contain selected constraint face id(s): %1. "
            "The external Netgen path requires Netgen surface numbers to match the selected OCCT face ids.")
            .arg(ids.join(QStringLiteral(", "))).toStdString());
    }
}

QString findNetgenBridgeScript()
{
    const QString envPath = qEnvironmentVariable("NETGEN_BRIDGE_SCRIPT");
    if (!envPath.isEmpty() && QFile::exists(envPath)) {
        return envPath;
    }

    const QDir appDir(QCoreApplication::applicationDirPath());
    const QStringList candidates = {
        appDir.absoluteFilePath("scripts/netgen_mesh_step.py"),
        appDir.absoluteFilePath("../../scripts/netgen_mesh_step.py"),
        QDir::current().absoluteFilePath("scripts/netgen_mesh_step.py")
    };
    for (const QString &candidate : candidates) {
        if (QFile::exists(candidate)) {
            return QDir::cleanPath(candidate);
        }
    }
    return QString();
}

bool isPythonRunner(const QString &netgenPath)
{
    const QString fileName = QFileInfo(netgenPath).fileName().toLower();
    return fileName == QStringLiteral("python.exe")
        || fileName == QStringLiteral("python3.exe")
        || fileName == QStringLiteral("python");
}

void runNetgen(const QString &netgenPath, const QString &stepFilePath, const QString &volPath, const QString &workDirectory, const QString &options)
{
    const QString absoluteStepFilePath = QFileInfo(stepFilePath).absoluteFilePath();
    QStringList arguments;
    if (isPythonRunner(netgenPath)) {
        const QString bridgeScript = findNetgenBridgeScript();
        if (bridgeScript.isEmpty()) {
            throw std::runtime_error("Netgen Python backend was found, but scripts/netgen_mesh_step.py was not found.");
        }
        arguments << bridgeScript;
        arguments << QDir::toNativeSeparators(absoluteStepFilePath);
        arguments << QDir::toNativeSeparators(volPath);
    } else {
        arguments << QStringLiteral("-batchmode");
        arguments << QStringLiteral("-geofile=%1").arg(QDir::toNativeSeparators(absoluteStepFilePath));
        arguments << QStringLiteral("-meshfile=%1").arg(QDir::toNativeSeparators(volPath));
    }
    if (!options.trimmed().isEmpty()) {
        arguments << splitDataLine(options.trimmed());
    }

    QProcess process;
    process.setWorkingDirectory(workDirectory);
    process.start(netgenPath, arguments);
    if (!process.waitForStarted(5000)) {
        throw std::runtime_error("Could not start Netgen. Set NETGEN_EXE, set NETGEN_PYTHON, or run scripts/download_netgen_windows.ps1.");
    }
    process.waitForFinished(-1);

    const QString output = QString::fromLocal8Bit(process.readAllStandardOutput())
        + QString::fromLocal8Bit(process.readAllStandardError());
    if (process.exitStatus() != QProcess::NormalExit || process.exitCode() != 0) {
        throw std::runtime_error(QString("Netgen failed:\n%1").arg(output.left(3000)).toStdString());
    }
    if (!QFile::exists(volPath)) {
        throw std::runtime_error("Netgen finished but did not write the expected .vol mesh file.");
    }
}

VolumeMesh convertNetgenMesh(const NetgenMesh &netgenMesh, const QSet<int> &constraintFaceIds)
{
    VolumeMesh mesh;
    mesh.nodes = netgenMesh.nodes;
    mesh.tetrahedra = netgenMesh.tetrahedra;
    mesh.boundaryFaces.reserve(netgenMesh.surfaceFaces.size());
    for (const NetgenSurfaceFace &face : netgenMesh.surfaceFaces) {
        const int marker = constraintFaceIds.contains(face.marker) ? face.marker : 0;
        mesh.boundaryFaces.push_back({face.a, face.b, face.c, marker});
        if (marker > 0) {
            mesh.constraintNodeIdsByMarker[marker].insert(face.a);
            mesh.constraintNodeIdsByMarker[marker].insert(face.b);
            mesh.constraintNodeIdsByMarker[marker].insert(face.c);
        }
    }
    return mesh;
}

} // namespace

QString NetgenVolumeMesher::findNetgenExecutable()
{
    const QString envPath = qEnvironmentVariable("NETGEN_EXE");
    if (!envPath.isEmpty() && QFile::exists(envPath)) {
        return envPath;
    }

    const QString appLocal = QDir(QCoreApplication::applicationDirPath()).absoluteFilePath("netgen.exe");
    if (QFile::exists(appLocal)) {
        return appLocal;
    }

    const QString projectLocal = QDir(QCoreApplication::applicationDirPath()).absoluteFilePath("../../extern/netgen/bin/netgen.exe");
    if (QFile::exists(projectLocal)) {
        return QDir::cleanPath(projectLocal);
    }

    const QString onPath = QStandardPaths::findExecutable("netgen");
    if (!onPath.isEmpty()) {
        return onPath;
    }

    const QString msys2Netgen = QStringLiteral("C:/msys64/ucrt64/bin/netgen.exe");
    if (QFile::exists(msys2Netgen)) {
        return msys2Netgen;
    }

    const QString envPython = qEnvironmentVariable("NETGEN_PYTHON");
    if (!envPython.isEmpty() && QFile::exists(envPython)) {
        return envPython;
    }

    const QDir appDir(QCoreApplication::applicationDirPath());
    const QString projectPython = appDir.absoluteFilePath("../../extern/netgen/python-env/Scripts/python.exe");
    if (QFile::exists(projectPython)) {
        return QDir::cleanPath(projectPython);
    }

    return QString();
}

VolumeMesh NetgenVolumeMesher::meshStepFile(
    const QString &stepFilePath,
    const QString &workDirectory,
    const QVector<int> &constraintFaceIds,
    const QString &netgenExecutable,
    const QString &netgenOptions)
{
    const QString netgenPath = netgenExecutable.isEmpty() ? findNetgenExecutable() : netgenExecutable;
    if (netgenPath.isEmpty()) {
        throw std::runtime_error("Netgen backend was not found. Run scripts/download_netgen_windows.ps1, set NETGEN_EXE, or set NETGEN_PYTHON.");
    }

    QDir workDir(workDirectory);
    if (!workDir.exists() && !workDir.mkpath(QStringLiteral("."))) {
        throw std::runtime_error("Could not create Netgen working directory.");
    }

    const QString baseName = QFileInfo(stepFilePath).completeBaseName().isEmpty()
        ? QStringLiteral("model")
        : QFileInfo(stepFilePath).completeBaseName();
    const QString volPath = workDir.absoluteFilePath(baseName + QStringLiteral("_netgen.vol"));
    runNetgen(netgenPath, stepFilePath, volPath, workDir.absolutePath(), netgenOptions);

    NetgenMesh netgenMesh = readNetgenVolFile(volPath);
    if (netgenMesh.tetrahedra.isEmpty()) {
        throw std::runtime_error("Netgen .vol did not contain tetrahedral volume elements.");
    }

    const QSet<int> constraintFaceIdSet(constraintFaceIds.begin(), constraintFaceIds.end());
    remapNetgenSurfaceMarkersFromSelectedFaces(stepFilePath, netgenMesh, constraintFaceIdSet);
    validateConstraintMarkers(netgenMesh, constraintFaceIdSet);
    VolumeMesh mesh = convertNetgenMesh(netgenMesh, constraintFaceIdSet);
    mesh.nodePath = volPath;
    mesh.elementPath = volPath;
    mesh.vtkPath = workDir.absoluteFilePath(baseName + QStringLiteral("_netgen.vtk"));
    mesh.boundaryVtkPath = workDir.absoluteFilePath(baseName + QStringLiteral("_netgen.faces.vtk"));
    writeVolumeLegacyVtkFile(mesh.vtkPath, mesh);
    writeBoundaryLegacyVtkFile(mesh.boundaryVtkPath, mesh);
    return mesh;
}
